### ISSUE TITLE
FloodSpill algorithm that returns regions for further calculation

### ISSUE THREAD

**Issue by kenofori** [azsdaja/FloodSpill-CSharp#4]
Hi there,

Great Work on the algorithm.

Can you please guide how can i achieve following case with your amazing library?

I have a 2D Array of Colors (100x100), 

imagine this this 2d array represent following pixel art image.
https://cdn4.vectorstock.com/i/1000x1000/75/98/pixel-art-golden-coin-dollar-retro-video-game-vector-15947598.jpg

Instead of actually changing colors by flood fill, what i want is that algorithm visit all the cells, and return list of all the colorable connected regions's cells

for example if you look at image. it has 5 white color regions (4 on corners, and 1 inside). So algorithm will return 5 arrays where each array will contain point (x,y) location of each cell that makes a single region.

This way i can process each region differently.

please advise and Thank you very much for creating an efficient library.

**Comment by azsdaja** [comment]
Hi and thanks for nice words!

If I understood correctly, you want to find all contiguous regions in the image, preferably only these having a specific color.

The solution is to run the algorithm separately for each single pixel, but to skip it if the pixel has already been visited.

You can take a look at the following piece of code:

``` csharp
[Test]
public void FindContiguousRegions()
{
	int xSize = 10, ySize = 10;
	var colors = new int[xSize, ySize];
	colors[3, 4] = 5;
	colors[4, 4] = 5;
	colors[7, 7] = 5;
	var markMatrix = new int[xSize, ySize];
	var visitedMatrix = new bool[xSize, ySize];
        var regions = new List<List<Position>>();
	var floodSpiller = new FloodScanlineSpiller();

	for (int startX = 0; startX < xSize; startX++)
	{
		for (int startY = 0; startY < ySize; startY++)
		{
                    if (visitedMatrix[startX, startY]) 
/*if you're interested only in specific color, 
add a condition like this: colors[startX, startY] == desiredColor*/
                        continue;

		    var currentRegion = new List<Position>();
		    regions.Add(currentRegion);
                    int sourceColor = colors[startX, startY];

		    var floodParameters = new FloodParameters(startX, startY)
		    {
                        ProcessStartAsFirstNeighbour = true,
                        Qualifier = (x, y) => !visitedMatrix[x, y] && colors[x, y] == sourceColor,
		        NeighbourProcessor = (x, y, mark) =>
		        {
		            visitedMatrix[x, y] = true;
		            currentRegion.Add(new Position(x, y));
		        },
		    };
		    floodSpiller.SpillFlood(floodParameters, markMatrix);
        }
    }

    Console.WriteLine($"Regions: {regions.Count}");
	for (int i = 0; i < regions.Count; i++)
	{
		var region = regions[i];
		Console.WriteLine($"Region {i}: color is {colors[region[0].X, region[0].Y]}, size is {region.Count}");
	}
}
```

The result will be:
```
Regions: 3
Region 0: color is 0, size is 97
Region 1: color is 5, size is 2
Region 2: color is 5, size is 1
```

Is that what you needed?

**Comment by kenofori** [comment]
Based on the output, this is exactly what im looking for
thank you very much, ill test this code and let you know how it goes
thanks again :)

**Comment by kenofori** [comment]
Hi Again,

I'm having difficulty turning these positions into sub 2d arrays
http://csharphelper.com/blog/2017/10/make-subarray-extension-methods-in-c/
![region to sub rectangular array](https://user-images.githubusercontent.com/30837872/58121562-27805e80-7c21-11e9-89e8-dfd7bedbfa61.png)

Can you please assist?

**Comment by azsdaja** [comment]
So you need to have a separate 2D array for each contiguous region you find? I would suggest the following solution:
1. Declare `minX, minY, maxX` and `maxY` variables and find them for each of your regions - you can add some code to `NeighbourProcessor` function so that it checks if `x` or `y` of the processed position are lowest or highest and if so, modify the proper variable.
2. Then use the function from the article you posted declared as `public static T[,] SubArray<T>(this T[,] values,
    int row_min, int row_max, int col_min, int col_max)` in order to get the array containing your region.

**Comment by kenofori** [comment]
Thank you very much,
i have few issues directly related to library so gonna create new issue for it.

**Comment by kenofori** [comment]
Update:
Thank you very much, your algorithm is working AWESOME
Now only thing remaining is to test on mobile

**Comment by azsdaja** [comment]
Regarding your question about not including diagonal movement in the algorithm — just use `NeighbourhoodType = NeighbourhoodType.Four` in FloodParameters initializer.

**Comment by kenofori** [comment]
How can i get the only the outer region? for example, in attached image i can get region for all the outer white area and then perform further operations on it such as changing outer white to transparent

https://ih0.redbubble.net/image.111696035.6884/pp,550x550.u4.jpg
