### ISSUE TITLE
Work on a Flattened 2D Array

### ISSUE THREAD

**Issue by kenofori** [azsdaja/FloodSpill-CSharp#5]
Hi there,

Usually in image related formats return pixel data in a flattened 2D Array. So how can we use Flood Spill in that situation?
https://docs.unity3d.com/ScriptReference/Texture2D.GetPixels.html

Thanks

**Comment by azsdaja** [comment]
Hi,
In Unity you can access pixels by x and y coordinates using GetPixel method on your texture (https://docs.unity3d.com/ScriptReference/Texture2D.GetPixel.html).
You probably can also write a helper method looking more or less like this (it may be wrong but I bet you can get it to work if you experiment a little):
```csharp
GetPixel(int x, int y, Colors[] colors, int width)
{
   return colors[y*width + x];
}
```

**Comment by azsdaja** [comment]
@kenofori did it work for you?

**Comment by kenofori** [comment]
Thank you for asking, I was able to make your proposed Region Find Solutionwork with flattended Colors Array. However i really wish if FloodSpill handles flattended array internally to save extra calculations.
For example, i had to switch between one d and 2d index like in code.






`
var markMatrix = new int[texture2D.width, texture2D.height];        
var regions = new List<List<AVOPointMD>>(texture2D.width);        
var visitedCells = new List<int>(colors.Length);


for (int i = 0; i < colors.Length; i++)
{
            
            Color currentColor = colors[i];

            
            //do custom grid generation work here which relys on flattened array          



            if (visitedCells.Contains(i) || currentColor == Color.clear)
            {
                continue;

            }



            List<AVOPointMD> currentRegion = new List<AVOPointMD>();
            regions.Add(currentRegion);

             Point current2DIndex = Get2DIndex(i, texture2D.width);

            var floodParameters = new FloodParameters(current2DIndex.X, current2DIndex.Y)
            {
                ProcessStartAsFirstNeighbour = true,
                Qualifier = delegate(int x, int y)
                {

                    int oneDIndex = Get1DIndex(x, y, texture2D.width);
                    
                   
                    return !visitedCells.Contains(oneDIndex) && color32s[oneDIndex] == currentColor;

                },
                NeighbourProcessor = (x, y, mark) =>
                {
                    
                    AVOPointMD visitedPoint = new AVOPointMD(y, x, Get1DIndex(x, y, texture2D.width));

                    visitedCells.Add(visitedPoint.OneDIndex);
                    
                    currentRegion.Add(visitedPoint);
                },
            };
            
            
            
            new FloodScanlineSpiller().SpillFlood(floodParameters, markMatrix);
            
            
            
            
        }



`



So ideally, i'd prefer flattened variations like that



`
var markCells= new List<int>(colors.Length);  
var regions = new List<List<int>>(texture2D.width);        
var visitedCells = new List<int>(colors.Length);


for (int i = 0; i < colors.Length; i++)
{
            
            Color currentColor = colors[i];

            
            //do custom grid generation work here which relys on flattened array          



            if (visitedCells.Contains(i) || currentColor == Color.clear)
            {
                continue;

            }



            List<int> currentRegion = new List<int>();
            regions.Add(currentRegion);



            var floodParameters = new FloodParameters(i, texture2D.width)
            {
                ProcessStartAsFirstNeighbour = true,

                QualifierOneD = delegate(int oneDIndex)
                {

                   return !visitedCells.Contains(oneDIndex) && color32s[oneDIndex] == currentColor;

                },
                NeighbourProcessorOneD = (oneDIndex, mark) =>
                {                   

                    visitedCells.Add(oneDIndex);
                    
                    currentRegion.Add(oneDIndex);
                },
            };
            
            
            
            new FloodScanlineSpiller().SpillFlood(floodParameters, markCells);
            
            
            
            
        }



`


Thanks

**Comment by azsdaja** [comment]
I get it. But you would like to have these QualifierOneD, NeighbourProcessorOneD for convenience or because of performance gains? I think that the performance gain from it would be very small. If you have problems with performance with current code it's probably because you're calling `visitedCells.Contains(i)` at least once for each cell which is O(cells<sup>2</sup>). I'd suggest using an array (either one- or two-dimensional) for checking if a cell has been visited, like I described in #4.

**Comment by kenofori** [comment]
Update: your library worked great on mobile, thank you for amazing work.

As you know on mobile we have to be careful of performance so i want to use Datastructures that are easily poolable. For example ill replace visitedCells from list to Dictionary as i can reuse it by clearing instead of instantiating. Problem with Array is that ill have to make a new copy as ill be dealing with random sizes images.

I can live with current code but can i avoid following line? is it necessary? Again, i cant resue this 2d array because sizes will be different.
 var markMatrix = new int[texture2D.width, texture2D.height];

**Comment by azsdaja** [comment]
If you use arrays big enough, you'll be able to pool them.
For example, if your images are usually 300x300, 500x500, 700x700, you can create an array with relatively safe size like `var visitedPositions = new bool[1000x1000];` and unless you have an image bigger than 1000x1000 you can use it for smaller images. You can just clear it after every run of the algorithm. If you have a bigger image, you must allocate a new array (maybe 1.5 size of the big image) and assign it to `visitedPositions`.
And you can do the same with `markMatrix` (which you can't get rid of because it's crucial for FloodSpill). If you have `markMatrix` bigger than the processed image, just add `BoundsRestriction = new FloodBounds(texture2D.width, texture2D.height)` to FloodParameters initializer.
If you'd like, I can tell you how you could get rid of `visitedPositions` matrix, so that you have one big array less.
By the way, may I know what project are you working on?

**Comment by kenofori** [comment]
Thank you for detailed explanation, yes i can use a 1000x1000 because thats the max size ill ever have
and BoundsRestriction is a great feature to assist in reussability existing big array..

I'm actually working on a image based games that will let user drag drop picture pieces to create a full picture. its in very early stages as i just starting to implement gameplay.

Thanks :)

**Comment by kenofori** [comment]
@azsdaja Im more than happy now with 2d array based approach because i can now reuse these intialized arrays for other game modes.

there is one last concern though, lib uses rectanglur array. is there any possibility that it can take a jagged array. jagged will still be rectangular but will perform better on mobile.

thanks

**Comment by azsdaja** [comment]
Hi, I'll respond you within a day.

**Comment by azsdaja** [comment]
I'd definitely like to consider using a jagged array — maybe we'll get some performance gain from that. However it will also mean more memory allocation.
I recently don't have time for giving it a try. Feel free to do the modifications and compare the results with the original (the solution already contains some benchmarking code).

**Comment by kenofori** [comment]
even if we keep rect array, there are still some areas where we can make optimizations e.g.

`protected virtual void InitializeMarkMatrix()
    {
      for (int index1 = 0; index1 < this.MarkMatrix.GetLength(0); ++index1)
      {
        for (int index2 = 0; index2 < this.MarkMatrix.GetLength(1); ++index2)
          this.MarkMatrix[index1, index2] = int.MaxValue;
      }
    }`

for example doing getLength every time, we do it once
`int length1 = this.MarkMatrix.GetLength(0);
      int length2 = this.MarkMatrix.GetLength(1);`

thanks
